doctrine_migrations:
    transactional: false # this will add `public function isTransactional(): bool { return false; }` to generated migrations
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    enable_profiler: '%kernel.debug%'
    storage:
        table_storage:
            table_name: migration_versions
