version: "3"

services:
  react:
      profiles: ['', docker]
      command: "npm run dev"
      build:
          context: ./front
          dockerfile: Dockerfile
      working_dir: /app/frontend
      volumes:
          - ./front:/app/frontend
      ports:
          - 63281:63281
  symfony:
      profiles: ['', docker]
      command: "make serve.php"
      environment:
            DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-password}@database:5432/${POSTGRES_DB:-app}
      build:
          context: ./back
          dockerfile: Dockerfile
      working_dir: /app/backend
      volumes:
          - ./back:/app/backend
      ports:
          - 63280:63280
          - 63290:63290
  database:
    profiles: ['', local, docker]
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
