version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "62529:5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    profiles: ['', docker, local, backend]
    image: schickling/mailcatcher
    ports: ["1025", "62551:1080"]
###< symfony/mailer ###
