Riser:
  type: object
  config:
    description: 'A riser'
    fields:
      uid:
        type: ULID!

      name:
        type: String!

      beehive:
        type: Beehive
        description: 'La Ruche sur laquelle la hausse est installée.'

      frames:
        type: '[Frame!]!'
        description: 'Frames of the riser'

      createdAt:
        type: DateTime!
        description: 'Date de création'

      updatedAt:
        type: DateTime!
        description: 'Date de modification'

      deleteAt:
        type: DateTime!
        description: 'Date de suppression'
