Mutation:
  type: object
  config:
    fields:

      User:
        type: UserMutations!
        resolve: "@=mutation('NamespacedMutation')"

      Apiary:
        type: ApiaryMutations!
        resolve: "@=mutation('NamespacedMutation')"
