Mutation:
  type: object
  config:
    fields:
      User:
        type: UserMutations!
        resolve: "@=mutation('NamespacedMutation')"

      Apiary:
        type: ApiaryMutations!
        resolve: "@=mutation('NamespacedMutation')"

      Beehive:
        type: BeehiveMutations!
        resolve: "@=mutation('NamespacedMutation')"

      Riser:
        type: RiserMutations!
        resolve: "@=mutation('NamespacedMutation')"

      Frame:
        type: FrameMutations!
        resolve: "@=mutation('NamespacedMutation')"

      Buying:
        type: BuyingMutations!
        resolve: "@=mutation('NamespacedMutation')"
