Query:
  type: object
  config:
    fields:
      User:
        type: UserQueries!
        resolve: "@=query('NamespacedQuery')"

      Apiary:
        type: ApiaryQueries!
        resolve: "@=query('NamespacedQuery')"

      Beehive:
        type: BeehiveQueries!
        resolve: "@=query('NamespacedQuery')"

      Riser:
        type: RiserQueries!
        resolve: "@=query('NamespacedQuery')"

      Frame:
        type: FrameQueries!
        resolve: "@=query('NamespacedQuery')"

      Buying:
        type: BuyingQueries!
        resolve: "@=query('NamespacedQuery')"
